### ISSUE TITLE
Could you please explain how to setup and use the tflite model in the Unity environment

### ISSUE THREAD

**Issue by cyz2727327** [bkunters/TFLite4Unity#5]
Hi,

I have been searching desperately for a solution of using TFlite model on Unity to develop for Android device, I want to build an Android app with augmented reality (ARCore) and artificial intelligence (TFlite), and your plug-in seems to have the best hope so far.

I do have some experience in Unity, but I have ZERO experience in TensorFlow and machine learning. I understand that the output of TensorFlow is a pre-trained model in .tflite format. Assume I can get a model ( there's a bunch online already) for a simple ML purpose (say object detection).

My main question is: how do I set up the environment in Unity to use this .tflite model? For example, a pretraining object tracking model should give me output as the target names and the bounding boxes. What should I do in Unity to make the use of this model? 

Please bear with me if this sounds extremely stupid, but I am so desperately in need of this information, and I cannot find it anywhere else.

PS: the TFLite Android link in your post is broken.

**Comment by bkunters** [comment]
Hi 

I have just resolved the problem with the project location. You can check out the link again. There you can find the sample code.

After your model has been trained you can export the model as a .tflite model unless you do not use unsupported layers in your model. You can have a look at the official docu.

Your neural network has the input layer which is a tensor with a specific size as well as your output layer. You can find out how I use these both layers inside the android project.

But I just realized I can automate generating new code for tflite models as the pattern is mostly similar. I just add it as a new feature idea now. @metul 

In the near future I will integrate the C++ library directly into Unity. So you can also work there.

Best luck.
